# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./...
  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: copy built binary
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{secret.HOST}}
          username: ${{secret.USERNAME}}
          key: ${{secret.PRIVATE_KEY}}
          port: 22
          source: "./test_ci_cd"
          target: "~/bin/"
          
